### PR TITLE
Updated readme file

### LINKED ISSUE #35: Deployment/build steps in README
Add some context and deployment/build steps in the README

### PR DESCRIPTION
**Pull request by Tanuj22**
Fixes #35

### CODE REVIEW

**Comment by Tanuj22** [comment]
@ajatprabha @anshulahuja98 Please check this.

**Comment by anshulahuja98** [comment]
Add some screenshots of the actual project. The UI, functionality etc.
Even perhaps add a brief about what the motivation/features of the projects are.

**Comment by anshulahuja98** [comment]
@Tanuj22 ?

**Comment by Tanuj22** [comment]
Forgot about this. Doing it now!

**Comment by anshulahuja98** [comment]
LGTM

**Pull request merged**
